/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Body: typeof import('./components/layout/body/Body.vue')['default']
    Breadcrumb: typeof import('./components/layout/breadcrumb/Breadcrumb.vue')['default']
    Content: typeof import('./components/layout/content/Content.vue')['default']
    Footer: typeof import('./components/layout/footer/Footer.vue')['default']
    Guide: typeof import('./components/guide/Guide.vue')['default']
    Header: typeof import('./components/layout/header/Header.vue')['default']
    HeaderAvatar: typeof import('./components/layout/header/HeaderAvatar.vue')['default']
    HeaderNotice: typeof import('./components/layout/header/HeaderNotice.vue')['default']
    HeaderSearch: typeof import('./components/layout/header/HeaderSearch.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    MBody: typeof import('./components/layout/body/MBody.vue')['default']
    MBreadcrumb: typeof import('./components/layout/breadcrumb/MBreadcrumb.vue')['default']
    MContent: typeof import('./components/layout/content/MContent.vue')['default']
    MFooter: typeof import('./components/layout/footer/MFooter.vue')['default']
    MHeader: typeof import('./components/layout/header/MHeader.vue')['default']
    MHeaderAvatar: typeof import('./components/layout/header/MHeaderAvatar.vue')['default']
    MHeaderNotice: typeof import('./components/layout/header/MHeaderNotice.vue')['default']
    MHeaderSearch: typeof import('./components/layout/header/MHeaderSearch.vue')['default']
    MSiderMenu: typeof import('./components/layout/sider/MSiderMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderMenu: typeof import('./components/layout/sider/SiderMenu.vue')['default']
  }
}
