/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Guide: typeof import('./components/guide/Guide.vue')['default']
    IAsideMenu: typeof import('./components/layout/sider/IAsideMenu.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    MAsideMenu: typeof import('./components/layout/sider/MAsideMenu.vue')['default']
    MBody: typeof import('./components/layout/body/MBody.vue')['default']
    MBreadcrumb: typeof import('./components/layout/breadcrumb/MBreadcrumb.vue')['default']
    MContent: typeof import('./components/layout/content/MContent.vue')['default']
    MFooter: typeof import('./components/layout/footer/MFooter.vue')['default']
    MHeader: typeof import('./components/layout/header/MHeader.vue')['default']
    MHeaderAvatar: typeof import('./components/layout/header/MHeaderAvatar.vue')['default']
    MHeaderNotice: typeof import('./components/layout/header/MHeaderNotice.vue')['default']
    MHeaderSearch: typeof import('./components/layout/header/MHeaderSearch.vue')['default']
    MSiderMenu: typeof import('./components/layout/sider/MSiderMenu.vue')['default']
    QSvg: typeof import('./components/svg/QSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
